rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
minKubeVersion: 1.18.0
writeStatusName: '""'
imagestream: false
debug: true
installType: upstream
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 20m
     memory: 320Mi

catalog:
  replicaCount: 1
  commandArgs: -configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 20m
     memory: 160Mi

package:
  replicaCount: 2
  maxUnavailable: 1
  maxSurge: 1
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 20m
     memory: 100Mi

monitoring:
  enabled: false
  namespace: monitoring
